const execute = require('./connectionHost');


const express = require('express');
const router = express.Router();

//LISTADO DE PEDIDOS PENDIENTES EN HOST
router.post("/pedidospendientes", async(req,res)=>{
    
    const { empnit , token} = req.body;
        
    let qry =`SELECT WEB_DOCUMENTOS.CODDOC, 
    WEB_DOCUMENTOS.CORRELATIVO, 
    WEB_DOCUMENTOS.CODVEN, 
    VENDEDORES.NOMVEN, 
    WEB_DOCUMENTOS.CODCLIENTE, 
    CLIENTES.NOMCLIENTE,
    ISNULL(WEB_DOCUMENTOS.TOTALCOSTO, 0) AS TOTALCOSTO, 
    WEB_DOCUMENTOS.TOTALVENTA, 
    ISNULL(WEB_DOCUMENTOS.FECHAENVIADO, '01/01/2018') AS FECHAENVIADO,
    ISNULL(WEB_DOCUMENTOS.FECHA, '01/01/2018') AS FECHA, 
    ISNULL(CLIENTES.NIT, 'SN') AS NITCLIE, 
    ISNULL(REPARTIDORES.DESREP, 'SN') AS DESREP, 
    WEB_DOCUMENTOS.CODST, 
    PARAM_STATUS.DESST,
    ISNULL(WEB_DOCUMENTOS.CODREP,0) AS CODREP,
    ISNULL(WEB_DOCUMENTOS.ENTREGADO,'NO') AS ENTREGADO,
    ISNULL(WEB_DOCUMENTOS.OBS,'SN') AS OBS
        FROM WEB_DOCUMENTOS LEFT OUTER JOIN
        PARAM_STATUS ON WEB_DOCUMENTOS.CODST = PARAM_STATUS.CODST LEFT OUTER JOIN
        REPARTIDORES ON WEB_DOCUMENTOS.CODREP = REPARTIDORES.CODREP AND WEB_DOCUMENTOS.EMPNIT = REPARTIDORES.EMPNIT AND 
        WEB_DOCUMENTOS.TOKEN = REPARTIDORES.TOKEN LEFT OUTER JOIN
        CLIENTES ON WEB_DOCUMENTOS.CODCLIENTE = CLIENTES.CODCLIENTE AND WEB_DOCUMENTOS.EMPNIT = CLIENTES.EMPNIT AND WEB_DOCUMENTOS.TOKEN = CLIENTES.TOKEN LEFT OUTER JOIN
        VENDEDORES ON WEB_DOCUMENTOS.CODVEN = VENDEDORES.CODVEN AND WEB_DOCUMENTOS.TOKEN = VENDEDORES.TOKEN AND WEB_DOCUMENTOS.EMPNIT = VENDEDORES.EMPNIT
        WHERE (WEB_DOCUMENTOS.TOKEN = '${token}') AND (WEB_DOCUMENTOS.EMPNIT = '${empnit}') AND (WEB_DOCUMENTOS.CODST<>3)`;

    
    execute.Query(res,qry);

});

//MARCA EL PEDIDO CON ENTREGADO

module.exports = router;